export interface InterviewQuestion {
  id: string
  category: string
  question: string
  difficulty: 'easy' | 'medium' | 'hard'
  tips: string[]
  sampleAnswer: string
  keyPoints: string[]
  xpReward: number
  timeLimit: number // in minutes
}

export const interviewCategories = [
  { id: 'all', name: 'All Questions', count: 20, icon: 'Grid' },
  { id: 'behavioral', name: 'Behavioral', count: 6, icon: 'Users' },
  { id: 'technical', name: 'Technical', count: 5, icon: 'Code' },
  { id: 'system-design', name: 'System Design', count: 4, icon: 'Layers' },
  { id: 'hr', name: 'HR Round', count: 5, icon: 'MessageCircle' },
]

export const interviewQuestions: InterviewQuestion[] = [
  // Behavioral Questions
  {
    id: 'tell-me-about-yourself',
    category: 'behavioral',
    question: 'Tell me about yourself.',
    difficulty: 'easy',
    tips: [
      'Keep it concise (2-3 minutes)',
      'Focus on professional background',
      'Highlight relevant experiences',
      'End with why you want this role',
    ],
    sampleAnswer: `I am a software engineer with 2 years of experience in full-stack development. I graduated from XYZ University with a degree in Computer Science. During my time at ABC Company, I worked on building scalable web applications using React and Node.js, where I led a team project that improved page load times by 40%. I am passionate about creating efficient, user-friendly solutions and am excited about this opportunity because it aligns with my goal of working on impactful products that reach millions of users.`,
    keyPoints: [
      'Brief introduction',
      'Educational background',
      'Relevant work experience',
      'Key achievements',
      'Why this role/company',
    ],
    xpReward: 25,
    timeLimit: 3,
  },
  {
    id: 'strengths-weaknesses',
    category: 'behavioral',
    question: 'What are your strengths and weaknesses?',
    difficulty: 'medium',
    tips: [
      'Be honest but strategic',
      'Give specific examples for strengths',
      'For weaknesses, show self-awareness',
      'Explain how you are improving your weakness',
    ],
    sampleAnswer: `My key strength is problem-solving. I enjoy breaking down complex issues into manageable parts. For example, when faced with a performance bottleneck in our application, I systematically profiled the code and identified that database queries were the culprit, leading to a 50% improvement after optimization.

As for a weakness, I sometimes tend to over-engineer solutions. I have learned to balance this by setting time constraints and focusing on MVP first, then iterating based on feedback.`,
    keyPoints: [
      'Specific strength with example',
      'Genuine weakness (not a hidden strength)',
      'Self-awareness',
      'Improvement actions',
    ],
    xpReward: 35,
    timeLimit: 4,
  },
  {
    id: 'challenging-project',
    category: 'behavioral',
    question: 'Describe a challenging project you worked on and how you handled it.',
    difficulty: 'medium',
    tips: [
      'Use the STAR method (Situation, Task, Action, Result)',
      'Choose a relevant technical challenge',
      'Highlight your problem-solving skills',
      'Quantify results if possible',
    ],
    sampleAnswer: `At my previous company, we needed to migrate our monolithic application to microservices while maintaining zero downtime. I led the database migration strategy, which was the most complex part. I implemented a dual-write pattern and gradual traffic shifting. The migration took 3 months and resulted in 60% improved scalability and 30% reduced operational costs.`,
    keyPoints: [
      'Clear situation description',
      'Your specific role/task',
      'Actions you took',
      'Measurable results',
    ],
    xpReward: 40,
    timeLimit: 5,
  },
  {
    id: 'teamwork-conflict',
    category: 'behavioral',
    question: 'Tell me about a time you had a conflict with a team member and how you resolved it.',
    difficulty: 'medium',
    tips: [
      'Show emotional intelligence',
      'Focus on resolution, not blame',
      'Demonstrate communication skills',
      'Show what you learned',
    ],
    sampleAnswer: `During a sprint, I disagreed with a colleague about the implementation approach for a feature. Instead of escalating, I suggested we both present our approaches to the team with pros and cons. After discussion, we realized a hybrid solution worked best. This taught me the value of open communication and that the best solutions often come from collaboration.`,
    keyPoints: [
      'Acknowledge the conflict professionally',
      'Your approach to resolution',
      'Positive outcome',
      'Lessons learned',
    ],
    xpReward: 40,
    timeLimit: 4,
  },
  {
    id: 'leadership-example',
    category: 'behavioral',
    question: 'Give an example of when you demonstrated leadership.',
    difficulty: 'hard',
    tips: [
      'Leadership is not just about titles',
      'Show initiative and influence',
      'Demonstrate how you motivated others',
      'Focus on team success over individual',
    ],
    sampleAnswer: `When our team lead was on leave during a critical release, I stepped up to coordinate the team. I organized daily standups, prioritized tasks, and ensured clear communication with stakeholders. I also mentored a junior developer who was struggling. We delivered on time, and the experience led to my promotion to tech lead.`,
    keyPoints: [
      'Taking initiative',
      'Coordinating/motivating team',
      'Problem-solving under pressure',
      'Positive outcome for team',
    ],
    xpReward: 50,
    timeLimit: 5,
  },
  {
    id: 'failure-learning',
    category: 'behavioral',
    question: 'Tell me about a time you failed and what you learned from it.',
    difficulty: 'medium',
    tips: [
      'Be genuine - everyone fails',
      'Show accountability',
      'Focus on the learning',
      'Explain how you have applied the lesson',
    ],
    sampleAnswer: `Early in my career, I deployed code without proper testing, causing a production outage. I immediately took responsibility and worked overnight to fix it. From this, I learned the importance of thorough testing and code reviews. I championed implementing a CI/CD pipeline with automated tests, which reduced our bug rate by 70%.`,
    keyPoints: [
      'Honest admission of failure',
      'Accountability',
      'Lessons learned',
      'Concrete improvements made',
    ],
    xpReward: 40,
    timeLimit: 4,
  },

  // Technical Questions
  {
    id: 'explain-rest-api',
    category: 'technical',
    question: 'Explain what REST API is and its principles.',
    difficulty: 'easy',
    tips: [
      'Cover the basics clearly',
      'Mention HTTP methods',
      'Explain key principles',
      'Give a practical example',
    ],
    sampleAnswer: `REST (Representational State Transfer) is an architectural style for designing networked applications. Key principles include: Statelessness - each request contains all information needed; Client-Server separation; Uniform interface using standard HTTP methods (GET, POST, PUT, DELETE); Resource-based URLs. For example, GET /api/users returns user list, POST /api/users creates a new user.`,
    keyPoints: [
      'Definition of REST',
      'Statelessness',
      'HTTP methods',
      'Resource-based design',
      'Practical examples',
    ],
    xpReward: 25,
    timeLimit: 3,
  },
  {
    id: 'database-indexing',
    category: 'technical',
    question: 'What is database indexing and when would you use it?',
    difficulty: 'medium',
    tips: [
      'Explain the concept simply',
      'Discuss trade-offs',
      'Mention types of indexes',
      'Give use cases',
    ],
    sampleAnswer: `Database indexing is a data structure that improves query speed by providing quick lookup paths. It is like a book index that helps find content without reading every page. You should index columns frequently used in WHERE clauses, JOINs, or ORDER BY. However, indexes slow down writes and use storage. Types include B-tree (default), Hash, and Full-text indexes.`,
    keyPoints: [
      'Purpose of indexing',
      'How it works',
      'When to use',
      'Trade-offs',
      'Index types',
    ],
    xpReward: 35,
    timeLimit: 4,
  },
  {
    id: 'time-complexity',
    category: 'technical',
    question: 'Explain Big O notation and give examples of different time complexities.',
    difficulty: 'medium',
    tips: [
      'Start with the definition',
      'Give practical examples',
      'Explain why it matters',
      'Compare different complexities',
    ],
    sampleAnswer: `Big O notation describes algorithm efficiency as input grows. O(1) is constant time - accessing array by index. O(log n) is logarithmic - binary search. O(n) is linear - iterating through array. O(n log n) is linearithmic - efficient sorting like merge sort. O(n²) is quadratic - nested loops. Understanding this helps choose efficient algorithms for scaling.`,
    keyPoints: [
      'Definition of Big O',
      'Common complexities with examples',
      'Practical implications',
      'Why it matters for scaling',
    ],
    xpReward: 35,
    timeLimit: 4,
  },
  {
    id: 'oops-concepts',
    category: 'technical',
    question: 'Explain the four pillars of Object-Oriented Programming.',
    difficulty: 'easy',
    tips: [
      'Cover all four pillars',
      'Give simple examples',
      'Show practical applications',
      'Keep explanations clear',
    ],
    sampleAnswer: `The four pillars are: 1) Encapsulation - bundling data and methods, hiding internal state (private variables with public getters/setters). 2) Inheritance - creating new classes from existing ones (Dog extends Animal). 3) Polymorphism - same interface, different implementations (method overriding). 4) Abstraction - showing only essential features (abstract classes/interfaces).`,
    keyPoints: [
      'Encapsulation with example',
      'Inheritance with example',
      'Polymorphism with example',
      'Abstraction with example',
    ],
    xpReward: 30,
    timeLimit: 4,
  },
  {
    id: 'microservices-vs-monolith',
    category: 'technical',
    question: 'What are the differences between microservices and monolithic architecture?',
    difficulty: 'hard',
    tips: [
      'Compare key characteristics',
      'Discuss pros and cons of each',
      'Mention when to use which',
      'Show real-world understanding',
    ],
    sampleAnswer: `Monolithic architecture is a single deployable unit - simpler to develop and test but harder to scale and modify. Microservices break applications into independent services - better scalability, technology flexibility, and team autonomy, but add complexity in deployment, monitoring, and data consistency. Choose monolith for MVPs/small teams, microservices for large, scaling applications.`,
    keyPoints: [
      'Definition of each',
      'Pros and cons comparison',
      'Scalability differences',
      'When to use each',
    ],
    xpReward: 50,
    timeLimit: 5,
  },

  // System Design Questions
  {
    id: 'design-url-shortener',
    category: 'system-design',
    question: 'How would you design a URL shortening service like bit.ly?',
    difficulty: 'hard',
    tips: [
      'Start with requirements clarification',
      'Discuss high-level design first',
      'Address scalability',
      'Consider edge cases',
    ],
    sampleAnswer: `Requirements: Generate short URLs, redirect to original, handle high traffic. Design: API service for creation/redirection, database for URL mappings (key-value store like Redis), unique ID generation (base62 encoding). Scale with load balancers, database sharding by key range, caching popular URLs. Handle collisions with retry logic.`,
    keyPoints: [
      'Requirements gathering',
      'Core components',
      'ID generation strategy',
      'Scalability approach',
      'Edge cases',
    ],
    xpReward: 60,
    timeLimit: 15,
  },
  {
    id: 'design-rate-limiter',
    category: 'system-design',
    question: 'Design a rate limiter for an API.',
    difficulty: 'medium',
    tips: [
      'Explain different algorithms',
      'Discuss trade-offs',
      'Consider distributed systems',
      'Address implementation details',
    ],
    sampleAnswer: `A rate limiter controls request frequency. Algorithms: Token Bucket (flexible, allows bursts), Sliding Window (precise), Fixed Window (simple). Implementation: Track requests per user/IP using Redis. For distributed systems, use centralized storage or sticky sessions. Return 429 Too Many Requests when exceeded. Consider: granularity, headers for remaining quota, grace periods.`,
    keyPoints: [
      'Purpose of rate limiting',
      'Algorithm options',
      'Storage considerations',
      'Distributed challenges',
      'Client feedback',
    ],
    xpReward: 50,
    timeLimit: 10,
  },
  {
    id: 'design-notification-system',
    category: 'system-design',
    question: 'How would you design a notification system?',
    difficulty: 'hard',
    tips: [
      'Consider multiple channels',
      'Think about scale and reliability',
      'Address user preferences',
      'Handle failures gracefully',
    ],
    sampleAnswer: `Support email, SMS, push notifications. Components: Notification Service (API), Message Queue (Kafka) for reliability, Worker Services per channel, Template Engine, User Preferences Store. Features: priority levels, batching, retry logic, rate limiting per user. Track delivery status and provide analytics. Use third-party providers (SendGrid, Twilio) with fallbacks.`,
    keyPoints: [
      'Multi-channel support',
      'Async processing with queues',
      'User preferences',
      'Reliability/retry logic',
      'Observability',
    ],
    xpReward: 60,
    timeLimit: 15,
  },
  {
    id: 'design-cache-system',
    category: 'system-design',
    question: 'Explain how you would implement a caching strategy.',
    difficulty: 'medium',
    tips: [
      'Discuss different caching layers',
      'Explain cache invalidation strategies',
      'Consider consistency trade-offs',
      'Mention tools/technologies',
    ],
    sampleAnswer: `Caching layers: Browser cache, CDN for static assets, Application cache (Redis/Memcached), Database query cache. Strategies: Cache-aside (app manages), Write-through (sync write), Write-behind (async write). Invalidation: TTL, event-based, manual purge. Consider: cache warming, thundering herd prevention, consistency requirements. Redis is popular for its data structures and persistence.`,
    keyPoints: [
      'Caching layers',
      'Caching strategies',
      'Invalidation approaches',
      'Tools/technologies',
      'Trade-offs',
    ],
    xpReward: 45,
    timeLimit: 8,
  },

  // HR Questions
  {
    id: 'why-this-company',
    category: 'hr',
    question: 'Why do you want to work for our company?',
    difficulty: 'easy',
    tips: [
      'Research the company beforehand',
      'Align your goals with company values',
      'Be specific, not generic',
      'Show genuine enthusiasm',
    ],
    sampleAnswer: `I am impressed by your company\'s focus on innovation and user-centric products. Your recent launch of [specific product] shows commitment to solving real problems. I align with your engineering culture of continuous learning. Additionally, the opportunity to work with your tech stack and scale would accelerate my growth as an engineer.`,
    keyPoints: [
      'Company research evident',
      'Specific reasons, not generic',
      'Alignment with values/goals',
      'Genuine enthusiasm',
    ],
    xpReward: 25,
    timeLimit: 3,
  },
  {
    id: 'five-year-plan',
    category: 'hr',
    question: 'Where do you see yourself in 5 years?',
    difficulty: 'easy',
    tips: [
      'Show ambition but be realistic',
      'Align with the role/company path',
      'Focus on growth and impact',
      'Avoid mentioning leaving the company',
    ],
    sampleAnswer: `In 5 years, I see myself as a senior engineer or tech lead, having grown technically and in leadership skills. I want to have mentored junior developers and contributed to significant projects. I am particularly interested in [relevant domain] and hope to become a subject matter expert while continuing to learn new technologies.`,
    keyPoints: [
      'Career progression goals',
      'Technical and leadership growth',
      'Alignment with company trajectory',
      'Continuous learning mindset',
    ],
    xpReward: 25,
    timeLimit: 3,
  },
  {
    id: 'salary-expectations',
    category: 'hr',
    question: 'What are your salary expectations?',
    difficulty: 'hard',
    tips: [
      'Research market rates beforehand',
      'Give a range, not a fixed number',
      'Focus on total compensation',
      'Be confident but flexible',
    ],
    sampleAnswer: `Based on my research and experience level, I am looking at a range of [X to Y]. However, I am flexible and open to discussing the total compensation package including benefits, equity, and growth opportunities. I am more focused on finding the right role where I can contribute and grow.`,
    keyPoints: [
      'Research-backed range',
      'Flexibility shown',
      'Focus on total package',
      'Value-focused conclusion',
    ],
    xpReward: 35,
    timeLimit: 2,
  },
  {
    id: 'questions-for-us',
    category: 'hr',
    question: 'Do you have any questions for us?',
    difficulty: 'medium',
    tips: [
      'Always have questions prepared',
      'Ask about team/culture',
      'Show genuine interest in the role',
      'Avoid asking about salary/benefits first',
    ],
    sampleAnswer: `Yes, I would love to know: 1) What does success look like in this role in the first 6 months? 2) How does the team handle knowledge sharing and code reviews? 3) What are the biggest challenges the team is currently facing? 4) What opportunities are there for learning and professional development?`,
    keyPoints: [
      'Role-specific questions',
      'Team/culture questions',
      'Growth opportunities',
      'Genuine curiosity',
    ],
    xpReward: 30,
    timeLimit: 3,
  },
  {
    id: 'why-leaving-current',
    category: 'hr',
    question: 'Why are you leaving your current job?',
    difficulty: 'medium',
    tips: [
      'Stay positive, do not criticize',
      'Focus on what you seek, not what you escape',
      'Be honest but diplomatic',
      'Connect to the opportunity',
    ],
    sampleAnswer: `I have learned a lot in my current role and am grateful for the experience. Now I am seeking new challenges and opportunities to grow in [specific area]. This role excites me because it offers [specific opportunities] that align with my career goals. I am ready for the next step in my journey.`,
    keyPoints: [
      'Positive about current employer',
      'Focus on growth/opportunity',
      'Specific reasons for change',
      'Connection to new role',
    ],
    xpReward: 30,
    timeLimit: 3,
  },
]

export const difficultyColors = {
  easy: 'text-green-500 bg-green-500/10 border-green-500/30',
  medium: 'text-yellow-500 bg-yellow-500/10 border-yellow-500/30',
  hard: 'text-red-500 bg-red-500/10 border-red-500/30',
}
